import {StyleSheet} from 'react-native';
import {Color} from '../../constants/color.constant';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    position: 'relative',
  },
  thumbnailListItemContainer: {
    display: 'flex',
    borderWidth: 1,
    borderColor: '#EBEBEB',
    borderRadius: 6,
    backgroundColor: '#FFFFFF',
  },
  thumbnailContainer: {
    width: '100%',
    height: 160,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    borderBottomWidth: 0.8,
    borderBottomColor: '#EBEBEB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  recordIconBlueContainer: {
    backgroundColor: Color.WHITE,
    width: 40,
    height: 40,
    paddingTop: 2.5,
    paddingLeft: 2,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
  },
  recordIconGrayContainer: {
    backgroundColor: '#333333',
    width: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
  },
  playIconContainer: {
    backgroundColor: Color.WHITE,
    width: 40,
    height: 40,
    paddingTop: 2,
    paddingLeft: 2,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
  },
  thumbnailRecordItemContainer: {
    position: 'absolute',
    width: '100%',
    height: 160,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    backgroundColor: '#32C5FF',
  },
  recordText: {
    color: 'white',
    opacity: 0.8,
    fontSize: 12,
    fontWeight: '500',
  },
  questionTextOnTumbnail: {
    width: '100%',
    fontWeight: '600',
    fontSize: 14,
    color: 'white',
  },
  questionTextWidthBgOnTumbnail: {
    position: 'absolute',
    bottom: 0,
    fontWeight: '600',
    fontSize: 12,
    color: 'white',
    padding: 5,
    backgroundColor: 'rgba(26, 26, 26, 0.9)',
  },
  contentsOnThumbnailContainer: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    gap: 6,
  },
  itemTitle: {
    width: '95%',
  },
  dateOnThumbnail: {
    position: 'absolute',
    zIndex: 1000,
    right: 18,
    top: 14,
  },
  description: {
    fontSize: 16,
    fontWeight: '400',
    color: '#A9A9A9',
  },
  profileContainer: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    paddingLeft: 16,
    marginTop: 40,
    marginBottom: 40,
  },
  chipContainer: {
    display: 'none',
  },
  chipItem: {
    height: 26,
    borderRadius: 16,
    paddingTop: 4,
    paddingBottom: 4,
    paddingLeft: 12,
    paddingRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 17,
  },
  chipText: {
    fontSize: 14,
    letterSpacing: 0.25,
  },
  questionText: {
    flex: 1,
  },
  onlyTextContent: {
    fontWeight: '400',
    fontSize: 14,
    marginBottom: 15,
    lineHeight: 21,
    color: '#B4B3B3',
  },
  dissolveView: {
    width: '100%',
    height: '100%',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(51, 51, 51, 0.8)',
  },
  thumbUpIcon: {
    width: 20,
    height: 20,
    opacity: 0.5,
    marginRight: 5,
    flexBasis: 20,
  },
  contentsContainer: {
    padding: 16,
    justifyContent: 'center',
  },
  videoContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    width: '100%',
  },
  video: {
    width: '100%',
    height: '100%',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
  },
  contentsOnThumbnail: {
    height: '100%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'black',
  },
  iconsOnThumbnail: {
    flexDirection: 'row',
    gap: 3,
    marginBottom: 2,
  },
  questionContainer: {
    width: '90%',
  },
  readMoreButton: {
    backgroundColor: Color.PRIMARY_LIGHT,
    justifyContent: 'center',
    alignItems: 'center',
    width: 43,
    height: 43,
    borderRadius: 50,
  },
});
