import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    position: 'relative',
  },
  thumbnailListItemContainer: {
    display: 'flex',
    height: 240,
    borderWidth: 1,
    borderColor: '#EBEBEB',
    borderRadius: 6,
    backgroundColor: '#FFFFFF',
  },
  thumbnailItemContainer: {
    width: '100%',
    height: 160,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    borderBottomWidth: 0.8,
    borderBottomColor: '#EBEBEB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  recordIconContainer: {
    position: 'absolute',
    alignItems: 'center',
    gap: 16,
  },
  thumbnailRecordItemContainer: {
    position: 'absolute',
    width: '100%',
    height: 160,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    backgroundColor: 'rgb(203 192 250)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  thumbnailRecordText: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '500',
    marginTop: 6,
  },
  textBox: {
    textAlign: 'left',
    maxWidth: '100%',
  },
  listTitle: {
    width: '65%',
    fontSize: 16,
    fontWeight: '600',
    color: '#333333',
  },
  dateTitle: {
    color: '#A9A9A9',
    fontSize: 12,
    marginLeft: 'auto',
  },
  description: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '400',
    color: '#A9A9A9',
  },
  thumbnailBox: {
    flex: 0.3,
    width: 94,
    height: 94,
  },
  thumbnailImage: {
    width: 94,
    height: 94,
    borderRadius: 10,
  },
  bottomRowBox: {
    position: 'absolute',
    width: '100%',
    bottom: 0,
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  dateText: {
    fontSize: 11,
    color: '#979797',
  },
  micIconBox: {},
  profileContainer: {
    flexDirection: 'row',
    height: 90,
    width: '100%',
    alignItems: 'center',
    borderBottomWidth: 0,
  },
  titleTextContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 23.5,
    marginBottom: 3,
  },
  contentTextContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  profileImage: {
    width: 68,
    height: 68,
    borderRadius: 50,
  },
  profileTitle: {
    fontWeight: '500',
    letterSpacing: 0.15,
    marginTop: 10,
    height: 20,
    lineHeight: 20,
  },
  profileText: {
    letterSpacing: 0.15,
    height: 20,
    lineHeight: 20,
  },
  chipContainer: {
    display: 'none',
  },
  chipItem: {
    height: 26,
    borderRadius: 16,
    paddingTop: 4,
    paddingBottom: 4,
    paddingLeft: 12,
    paddingRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 17,
  },
  chipText: {
    fontSize: 14,
    letterSpacing: 0.25,
  },
  heroAvatarIcon: {
    marginLeft: 20,
    marginRight: 20,
    backgroundColor: '#A9A9A9',
  },
  questionText: {
    fontSize: 14,
    color: '#999999',
    marginBottom: 25,
    fontWeight: 600,
  },
  onlyTextContent: {
    fontWeight: '400',
    fontSize: 14,
    marginBottom: 15,
    lineHeight: 21,
    color: '#B4B3B3',
  },
  dissolveView: {
    width: '100%',
    height: '100%',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(51, 51, 51, 0.8)',
  },
});
