import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  kakaoLoginButtonContainer: {
    flexDirection: 'row',
    height: 48,
    backgroundColor: '#FFE812',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4,
    marginBottom: 8,
  },
  kakaoLoginFont: {
    fontFamily: 'Pretendard Regular',
    fontWeight: 'bold',
    fontSize: 16,
  },
  appleLoginButtonContainer: {
    flexDirection: 'row',
    height: 48,
    backgroundColor: '#000000',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4,
    marginBottom: 8,
  },
  appleLoginFont: {
    fontFamily: 'Pretendard Regular',
    fontWeight: 'bold',
    fontSize: 16,
    color: '#FFFFFF',
  },
  appleLogo: {
    fontFamily: 'Pretendard Regular',
    fontWeight: 'bold',
    fontSize: 20,
    color: '#FFFFFF',
  },
  generalLoginButtonContainer: {
    flexDirection: 'row',
    height: 48,
    backgroundColor: '#343666',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4,
    marginBottom: 8,
  },
  generalLoginFont: {
    fontFamily: 'Pretendard Regular',
    fontWeight: 'bold',
    fontSize: 16,
    color: '#FFFFFF',
  },
  otherLoginButtonContainer: {
    flexDirection: 'row',
    height: 48,
    backgroundColor: '#F4F4F4',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4,
  },
  otherLoginFont: {
    fontFamily: 'Pretendard Regular',
    fontWeight: 'bold',
    fontSize: 16,
  },
  socialLoginIcon: {
    width: 16,
    height: 16,
    marginRight: 4,
  },
  coloredButtonContainer: {
    flexDirection: 'row',
    height: 48,
    backgroundColor: '#343666',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4,
  },
  coloredButtonFont: {
    fontFamily: 'Pretendard Regular',
    fontWeight: 'bold',
    fontSize: 16,
    color: '#FFFFFF',
  },
});
