/**
 * This file was generated with the help of @react-native/codegen.
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the codegen is re-executed.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

import type {TurboModule} from 'react-native/Libraries/TurboModule/RCTExport';
import {TurboModuleRegistry} from 'react-native';

export interface Spec extends TurboModule {
  readonly sendSharedData: (eventName: string, data: string) => void;
  readonly testMethod: () => Promise<string>;
  readonly getSharedData: () => Promise<{
    readonly type: string | null;
    readonly uri?: string;
    readonly uriList?: ReadonlyArray<string>;
  }>;
}

export default TurboModuleRegistry.getEnforcing<Spec>('LPShareModule');
